<<<<<<< HEAD
----------------------- ALTER DYNAMIC SCRIPT -------------------------------

SELECT * 
FROM (

SELECT CASE 
		WHEN [DATA_TYPE] = 'varchar' and bb.[CONSTRAINT_NAME] is not null
		THEN
		CONCAT('ALTER TABLE ' , aa.[TABLE_SCHEMA] ,'.', aa.[TABLE_NAME] , ' ALTER COLUMN [', aa.[COLUMN_NAME] , '] NVARCHAR(',CHARACTER_MAXIMUM_LENGTH,') NOT NULL')
		WHEN [DATA_TYPE] = 'varchar' and aa.[TABLE_NAME] not like '%hier%' and bb.[CONSTRAINT_NAME] is null
		THEN
		CONCAT('ALTER TABLE ' , aa.[TABLE_SCHEMA] ,'.', aa.[TABLE_NAME] , ' ALTER COLUMN [', aa.[COLUMN_NAME] , '] NVARCHAR(',CHARACTER_MAXIMUM_LENGTH,')')		
		WHEN [DATA_TYPE] = 'float' and bb.[CONSTRAINT_NAME] is not null and aa.NUMERIC_PRECISION < 38
		THEN
		CONCAT('ALTER TABLE ' , aa.[TABLE_SCHEMA] ,'.', aa.[TABLE_NAME] , ' ALTER COLUMN [', aa.[COLUMN_NAME] , '] DECIMAL(',aa.NUMERIC_SCALE,',',aa.NUMERIC_PRECISION,') NOT NULL')	
		WHEN [DATA_TYPE] = 'float' and bb.[CONSTRAINT_NAME] is not null and aa.NUMERIC_PRECISION > 38
		THEN
		CONCAT('ALTER TABLE ' , aa.[TABLE_SCHEMA] ,'.', aa.[TABLE_NAME] , ' ALTER COLUMN [', aa.[COLUMN_NAME] , '] DECIMAL(38,',aa.NUMERIC_PRECISION_RADIX,') NOT NULL')	
		WHEN [DATA_TYPE] = 'float' and bb.[CONSTRAINT_NAME] is null and aa.NUMERIC_PRECISION < 38
		THEN
		CONCAT('ALTER TABLE ' , aa.[TABLE_SCHEMA] ,'.', aa.[TABLE_NAME] , ' ALTER COLUMN [', aa.[COLUMN_NAME] , '] DECIMAL(',aa.NUMERIC_SCALE,',',aa.NUMERIC_PRECISION,')')	
		WHEN [DATA_TYPE] = 'float' and bb.[CONSTRAINT_NAME] is null and aa.NUMERIC_PRECISION > 38
		THEN
		CONCAT('ALTER TABLE ' , aa.[TABLE_SCHEMA] ,'.', aa.[TABLE_NAME] , ' ALTER COLUMN [', aa.[COLUMN_NAME] , '] DECIMAL(38,',aa.NUMERIC_PRECISION_RADIX,')')	
		WHEN [DATA_TYPE] = 'BIT'
		THEN
		CONCAT('ALTER TABLE ' , aa.[TABLE_SCHEMA] ,'.', aa.[TABLE_NAME] , ' ALTER COLUMN [', aa.[COLUMN_NAME] , '] INT')	
		END as alterColumnScript
FROM INFORMATION_SCHEMA.COLUMNS aa
LEFT JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE bb
ON aa.TABLE_SCHEMA = bb.TABLE_SCHEMA and aa.TABLE_NAME = bb.TABLE_NAME and aa.COLUMN_NAME = bb.COLUMN_NAME 
WHERE aa.[TABLE_SCHEMA] = 'LANDING' 
) aa

WHERE aa.[alterColumnScript] is not null



/* draft

SELECT CASE 
		WHEN [DATA_TYPE] = 'varchar' and [TABLE_NAME] not like '%hier%' and CONCAT([TABLE_NAME],[COLUMN_NAME]) not in (SELECT CONCAT([TABLE_NAME],[COLUMN_NAME]) FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE )
		THEN
		CONCAT('ALTER TABLE ' , [TABLE_SCHEMA] ,'.', [TABLE_NAME] , ' ALTER COLUMN ', [COLUMN_NAME] , ' NVARCHAR(',CHARACTER_MAXIMUM_LENGTH,')')
		END
FROM INFORMATION_SCHEMA.COLUMNS	

SELECT * FROM INFORMATION_SCHEMA.COLUMNS	

*/


------------------------- ADD CONSTRAINT DYNAMIC SCRIPT -------------------------------------

SELECT * , 
		CONCAT('ALTER TABLE ' , [TABLE_SCHEMA] ,'.',[TABLE_NAME] , ' DROP CONSTRAINT ' , [CONSTRAINT_NAME] )  as alterTableDropConstraintScript ,
		CONCAT('ALTER TABLE ',bb.TABLE_SCHEMA , '.', bb.TABLE_NAME , ' ADD CONSTRAINT ',bb.CONSTRAINT_NAME, ' PRIMARY KEY (',bb.ConcatColumn,')')  as addConstraintScript
FROM (
SELECT DISTINCT(ipk.TABLE_SCHEMA) , ipk.TABLE_NAME  , ipk.CONSTRAINT_NAME 
     ,
   STUFF((SELECT ',' + ipks.COLUMN_NAME 
          FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ipks
          WHERE ipks.[TABLE_NAME] = ipk.[TABLE_NAME]
          --ORDER BY USR_NAME
          FOR XML PATH('')), 1, 1, '') as ConcatColumn -- [SECTORS/USERS]
FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ipk
WHERE [TABLE_SCHEMA] = 'LANDING'
GROUP BY ipk.TABLE_SCHEMA , ipk.TABLE_NAME , ipk.CONSTRAINT_NAME

) bb



ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY DROP CONSTRAINT PK__DIMARCHP__2B24885725AA9910
ALTER TABLE LANDING.DIMDATE DROP CONSTRAINT PK__DIMDATE__91652A5A5DDD4A3C
ALTER TABLE LANDING.DIMPRODUCT DROP CONSTRAINT PK__DIMPRODU__5385C67AF9565BE8
ALTER TABLE LANDING.DIMSTOREREGION DROP CONSTRAINT PK__DIMSTORE__5902801973538989
ALTER TABLE LANDING.FCTSALES DROP CONSTRAINT PK__FCTSALES__D83D6D063E573777

ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [STOREREGIONNAME] NVARCHAR(150)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [BKPRODUCTFAMILYID] NVARCHAR(100)
ALTER TABLE LANDING.DIMDATE ALTER COLUMN [DATENAME] NVARCHAR(15)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [UNITSIZE] DECIMAL(38,2)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [COMPANYCODE] NVARCHAR(30)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [PRODUCTVARIANTDESCRIPTION] NVARCHAR(250)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [ROWISCURRENT] NVARCHAR(1)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [CASEPACK] DECIMAL(38,2)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [PACKSIZE] DECIMAL(38,2)
ALTER TABLE LANDING.FCTSALES ALTER COLUMN [COSTPRICE] DECIMAL(38,2)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [PACKWEIGHT] DECIMAL(38,2)
ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [REGIONCOUNTRY] NVARCHAR(255)
ALTER TABLE LANDING.FCTSALES ALTER COLUMN [INVOICELINENUMBER] NVARCHAR(20)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [STORESHORTNAME] NVARCHAR(150)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [PRODUCTVARIANT] NVARCHAR(50)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [UNITOFMEASURE] NVARCHAR(50)
ALTER TABLE LANDING.DIMDATE ALTER COLUMN [FISCALYEARQTR] NVARCHAR(8)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [PRODUCTFAMILYSHORTDESCRIPTION] NVARCHAR(100)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [PRODUCTBRAND] NVARCHAR(250)
ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [FOREIGNLOCAL] NVARCHAR(50)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [PRODUCTFAMILYGROUPCODE] NVARCHAR(50)
ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [ROWISCURRENT] NVARCHAR(1)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [PRODUCTFAMILYDESCRIPTION] NVARCHAR(400)
ALTER TABLE LANDING.DIMDATE ALTER COLUMN [MONTHNAME] NVARCHAR(10)
ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [REGIONALMANAGER] NVARCHAR(150)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [FOREIGNLOCAL] NVARCHAR(50)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [BKSTOREID] NVARCHAR(20)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [POSSYSTEM] NVARCHAR(50)
ALTER TABLE LANDING.DIMDATE ALTER COLUMN [DAYNAMEOFWEEK] NVARCHAR(10)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [PRODUCTFAMILYCODE] NVARCHAR(24)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [BKPRODUCTID] NVARCHAR(100)
ALTER TABLE LANDING.DIMDATE ALTER COLUMN [FISCALYEARMONTH] NVARCHAR(9)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [UPDATE_USER] NVARCHAR(100)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [ROWCHANGEREASON] NVARCHAR(200)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [CASEPACKSTATUS] NVARCHAR(10)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [RANGINGFLAG] NVARCHAR(20)
ALTER TABLE LANDING.FCTSALES ALTER COLUMN [QUANTITY] DECIMAL(38,2)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [MASTERBARCODE] NVARCHAR(100)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [STORENAME] NVARCHAR(255)
ALTER TABLE LANDING.FCTSALES ALTER COLUMN [SALESPRICE] DECIMAL(38,2)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [PRODUCTFAMILYGROUPDESCRIPTION] NVARCHAR(100)
ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [BKSTOREREGIONID] NVARCHAR(20)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [Old ProductBrand] NVARCHAR(250)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [ROWISCURRENT] NVARCHAR(1)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [REGIONALMANAGER] NVARCHAR(150)
ALTER TABLE LANDING.FCTSALES ALTER COLUMN [INVOICEHEADERNUMBER] NVARCHAR(100)
ALTER TABLE LANDING.DIMDATE ALTER COLUMN [FISCALWEEKNAME] NVARCHAR(50)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [ROWCHANGEREASON] NVARCHAR(200)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [STORELEDGERCODE] NVARCHAR(50)
ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [ROWCHANGEREASON] NVARCHAR(200)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [UPDATE_USER] NVARCHAR(100)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [STORECOUNTRYCODE] NVARCHAR(15)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [STOREMANAGER] NVARCHAR(150)
ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [REGIONNAME] NVARCHAR(255)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [GREATPLAINSCODE] NVARCHAR(20)

ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ADD CONSTRAINT PK__DIMARCHP__2B24885725AA9910 PRIMARY KEY (ARCHPRODUCTFAMILYKEY)
ALTER TABLE LANDING.DIMDATE ADD CONSTRAINT PK__DIMDATE__91652A5A5DDD4A3C PRIMARY KEY (DATEKEY)
ALTER TABLE LANDING.DIMPRODUCT ADD CONSTRAINT PK__DIMPRODU__5385C67AF9565BE8 PRIMARY KEY (PRODUCTKEY)
ALTER TABLE LANDING.DIMSTOREREGION ADD CONSTRAINT PK__DIMSTORE__5902801973538989 PRIMARY KEY (STOREREGIONKEY)
=======
----------------------- ALTER DYNAMIC SCRIPT -------------------------------

SELECT * 
FROM (

SELECT CASE 
		WHEN [DATA_TYPE] = 'varchar' and bb.[CONSTRAINT_NAME] is not null
		THEN
		CONCAT('ALTER TABLE ' , aa.[TABLE_SCHEMA] ,'.', aa.[TABLE_NAME] , ' ALTER COLUMN [', aa.[COLUMN_NAME] , '] NVARCHAR(',CHARACTER_MAXIMUM_LENGTH,') NOT NULL')
		WHEN [DATA_TYPE] = 'varchar' and aa.[TABLE_NAME] not like '%hier%' and bb.[CONSTRAINT_NAME] is null
		THEN
		CONCAT('ALTER TABLE ' , aa.[TABLE_SCHEMA] ,'.', aa.[TABLE_NAME] , ' ALTER COLUMN [', aa.[COLUMN_NAME] , '] NVARCHAR(',CHARACTER_MAXIMUM_LENGTH,')')		
		WHEN [DATA_TYPE] = 'float' and bb.[CONSTRAINT_NAME] is not null and aa.NUMERIC_PRECISION < 38
		THEN
		CONCAT('ALTER TABLE ' , aa.[TABLE_SCHEMA] ,'.', aa.[TABLE_NAME] , ' ALTER COLUMN [', aa.[COLUMN_NAME] , '] DECIMAL(',aa.NUMERIC_SCALE,',',aa.NUMERIC_PRECISION,') NOT NULL')	
		WHEN [DATA_TYPE] = 'float' and bb.[CONSTRAINT_NAME] is not null and aa.NUMERIC_PRECISION > 38
		THEN
		CONCAT('ALTER TABLE ' , aa.[TABLE_SCHEMA] ,'.', aa.[TABLE_NAME] , ' ALTER COLUMN [', aa.[COLUMN_NAME] , '] DECIMAL(38,',aa.NUMERIC_PRECISION_RADIX,') NOT NULL')	
		WHEN [DATA_TYPE] = 'float' and bb.[CONSTRAINT_NAME] is null and aa.NUMERIC_PRECISION < 38
		THEN
		CONCAT('ALTER TABLE ' , aa.[TABLE_SCHEMA] ,'.', aa.[TABLE_NAME] , ' ALTER COLUMN [', aa.[COLUMN_NAME] , '] DECIMAL(',aa.NUMERIC_SCALE,',',aa.NUMERIC_PRECISION,')')	
		WHEN [DATA_TYPE] = 'float' and bb.[CONSTRAINT_NAME] is null and aa.NUMERIC_PRECISION > 38
		THEN
		CONCAT('ALTER TABLE ' , aa.[TABLE_SCHEMA] ,'.', aa.[TABLE_NAME] , ' ALTER COLUMN [', aa.[COLUMN_NAME] , '] DECIMAL(38,',aa.NUMERIC_PRECISION_RADIX,')')	
		END as alterColumnScript
FROM INFORMATION_SCHEMA.COLUMNS aa
LEFT JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE bb
ON aa.TABLE_SCHEMA = bb.TABLE_SCHEMA and aa.TABLE_NAME = bb.TABLE_NAME and aa.COLUMN_NAME = bb.COLUMN_NAME 
WHERE aa.[TABLE_SCHEMA] = 'LANDING' 
) aa

WHERE aa.[alterColumnScript] is not null



/* draft

SELECT CASE 
		WHEN [DATA_TYPE] = 'varchar' and [TABLE_NAME] not like '%hier%' and CONCAT([TABLE_NAME],[COLUMN_NAME]) not in (SELECT CONCAT([TABLE_NAME],[COLUMN_NAME]) FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE )
		THEN
		CONCAT('ALTER TABLE ' , [TABLE_SCHEMA] ,'.', [TABLE_NAME] , ' ALTER COLUMN ', [COLUMN_NAME] , ' NVARCHAR(',CHARACTER_MAXIMUM_LENGTH,')')
		END
FROM INFORMATION_SCHEMA.COLUMNS	

SELECT * FROM INFORMATION_SCHEMA.COLUMNS	

*/


------------------------- ADD CONSTRAINT DYNAMIC SCRIPT -------------------------------------

SELECT * , 
		CONCAT('ALTER TABLE ' , [TABLE_SCHEMA] ,'.',[TABLE_NAME] , ' DROP CONSTRAINT ' , [CONSTRAINT_NAME] )  as alterTableDropConstraintScript ,
		CONCAT('ALTER TABLE ',bb.TABLE_SCHEMA , '.', bb.TABLE_NAME , ' ADD CONSTRAINT ',bb.CONSTRAINT_NAME, ' PRIMARY KEY (',bb.ConcatColumn,')')  as addConstraintScript
FROM (
SELECT DISTINCT(ipk.TABLE_SCHEMA) , ipk.TABLE_NAME  , ipk.CONSTRAINT_NAME 
     ,
   STUFF((SELECT ',' + ipks.COLUMN_NAME 
          FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ipks
          WHERE ipks.[TABLE_NAME] = ipk.[TABLE_NAME]
          --ORDER BY USR_NAME
          FOR XML PATH('')), 1, 1, '') as ConcatColumn -- [SECTORS/USERS]
FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ipk
WHERE [TABLE_SCHEMA] = 'LANDING'
GROUP BY ipk.TABLE_SCHEMA , ipk.TABLE_NAME , ipk.CONSTRAINT_NAME

) bb



ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY DROP CONSTRAINT PK__DIMARCHP__2B24885725AA9910
ALTER TABLE LANDING.DIMDATE DROP CONSTRAINT PK__DIMDATE__91652A5A5DDD4A3C
ALTER TABLE LANDING.DIMPRODUCT DROP CONSTRAINT PK__DIMPRODU__5385C67AF9565BE8
ALTER TABLE LANDING.DIMSTOREREGION DROP CONSTRAINT PK__DIMSTORE__5902801973538989
ALTER TABLE LANDING.FCTSALES DROP CONSTRAINT PK__FCTSALES__D83D6D063E573777

ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [STOREREGIONNAME] NVARCHAR(150)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [BKPRODUCTFAMILYID] NVARCHAR(100)
ALTER TABLE LANDING.DIMDATE ALTER COLUMN [DATENAME] NVARCHAR(15)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [UNITSIZE] DECIMAL(38,2)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [COMPANYCODE] NVARCHAR(30)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [PRODUCTVARIANTDESCRIPTION] NVARCHAR(250)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [ROWISCURRENT] NVARCHAR(1)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [CASEPACK] DECIMAL(38,2)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [PACKSIZE] DECIMAL(38,2)
ALTER TABLE LANDING.FCTSALES ALTER COLUMN [COSTPRICE] DECIMAL(38,2)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [PACKWEIGHT] DECIMAL(38,2)
ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [REGIONCOUNTRY] NVARCHAR(255)
ALTER TABLE LANDING.FCTSALES ALTER COLUMN [INVOICELINENUMBER] NVARCHAR(20)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [STORESHORTNAME] NVARCHAR(150)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [PRODUCTVARIANT] NVARCHAR(50)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [UNITOFMEASURE] NVARCHAR(50)
ALTER TABLE LANDING.DIMDATE ALTER COLUMN [FISCALYEARQTR] NVARCHAR(8)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [PRODUCTFAMILYSHORTDESCRIPTION] NVARCHAR(100)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [PRODUCTBRAND] NVARCHAR(250)
ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [FOREIGNLOCAL] NVARCHAR(50)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [PRODUCTFAMILYGROUPCODE] NVARCHAR(50)
ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [ROWISCURRENT] NVARCHAR(1)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [PRODUCTFAMILYDESCRIPTION] NVARCHAR(400)
ALTER TABLE LANDING.DIMDATE ALTER COLUMN [MONTHNAME] NVARCHAR(10)
ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [REGIONALMANAGER] NVARCHAR(150)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [FOREIGNLOCAL] NVARCHAR(50)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [BKSTOREID] NVARCHAR(20)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [POSSYSTEM] NVARCHAR(50)
ALTER TABLE LANDING.DIMDATE ALTER COLUMN [DAYNAMEOFWEEK] NVARCHAR(10)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [PRODUCTFAMILYCODE] NVARCHAR(24)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [BKPRODUCTID] NVARCHAR(100)
ALTER TABLE LANDING.DIMDATE ALTER COLUMN [FISCALYEARMONTH] NVARCHAR(9)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [UPDATE_USER] NVARCHAR(100)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [ROWCHANGEREASON] NVARCHAR(200)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [CASEPACKSTATUS] NVARCHAR(10)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [RANGINGFLAG] NVARCHAR(20)
ALTER TABLE LANDING.FCTSALES ALTER COLUMN [QUANTITY] DECIMAL(38,2)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [MASTERBARCODE] NVARCHAR(100)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [STORENAME] NVARCHAR(255)
ALTER TABLE LANDING.FCTSALES ALTER COLUMN [SALESPRICE] DECIMAL(38,2)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [PRODUCTFAMILYGROUPDESCRIPTION] NVARCHAR(100)
ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [BKSTOREREGIONID] NVARCHAR(20)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [Old ProductBrand] NVARCHAR(250)
ALTER TABLE LANDING.DIMPRODUCT ALTER COLUMN [ROWISCURRENT] NVARCHAR(1)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [REGIONALMANAGER] NVARCHAR(150)
ALTER TABLE LANDING.FCTSALES ALTER COLUMN [INVOICEHEADERNUMBER] NVARCHAR(100)
ALTER TABLE LANDING.DIMDATE ALTER COLUMN [FISCALWEEKNAME] NVARCHAR(50)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [ROWCHANGEREASON] NVARCHAR(200)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [STORELEDGERCODE] NVARCHAR(50)
ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [ROWCHANGEREASON] NVARCHAR(200)
ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ALTER COLUMN [UPDATE_USER] NVARCHAR(100)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [STORECOUNTRYCODE] NVARCHAR(15)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [STOREMANAGER] NVARCHAR(150)
ALTER TABLE LANDING.DIMSTOREREGION ALTER COLUMN [REGIONNAME] NVARCHAR(255)
ALTER TABLE LANDING.DIMSTORE ALTER COLUMN [GREATPLAINSCODE] NVARCHAR(20)

ALTER TABLE LANDING.DIMARCHPRODUCTFAMILY ADD CONSTRAINT PK__DIMARCHP__2B24885725AA9910 PRIMARY KEY (ARCHPRODUCTFAMILYKEY)
ALTER TABLE LANDING.DIMDATE ADD CONSTRAINT PK__DIMDATE__91652A5A5DDD4A3C PRIMARY KEY (DATEKEY)
ALTER TABLE LANDING.DIMPRODUCT ADD CONSTRAINT PK__DIMPRODU__5385C67AF9565BE8 PRIMARY KEY (PRODUCTKEY)
ALTER TABLE LANDING.DIMSTOREREGION ADD CONSTRAINT PK__DIMSTORE__5902801973538989 PRIMARY KEY (STOREREGIONKEY)
>>>>>>> 4f99eca6e50e597712e98aca908b2f46bfc868a0
ALTER TABLE LANDING.FCTSALES ADD CONSTRAINT PK__FCTSALES__D83D6D063E573777 PRIMARY KEY (CURRENCYKEY,CUSTOMERKEY,PRODUCTKEY,PROMOTIONKEY,STOREKEY,TRANSACTIONDATEKEY)